# Generated by Django 5.2.15 on 2026-07-22 10:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_club_alter_user_role_user_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coach_license',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.coach_license_upload_to),
        ),
        migrations.AddField(
            model_name='club',
            name='cvfa_membership',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='club',
            name='head_coach_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='club',
            name='is_school_affiliated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
