# Generated by Django 5.2.15 on 2026-08-24 12:08

import accounts.models
import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_club_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach_license',
            field=models.FileField(blank=True, null=True, storage=accounts.storage.SupabaseCoachLicenseStorage(), upload_to=accounts.models.coach_license_upload_to),
        ),
    ]
