# Generated by Django 5.2.15 on 2026-08-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_club_coach_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
