# Generated by Django 5.2.15 on 2026-08-24 15:50

import accounts.models
import accounts.storage
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach_license',
            field=models.FileField(blank=True, null=True, storage=accounts.storage.SupabaseCoachLicenseStorage(), upload_to=accounts.models.coach_license_upload_to, validators=[accounts.validators.validate_coach_license_upload]),
        ),
    ]
