# Generated by Django 5.2.17 on 2026-09-13 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_club_coach_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseProvisioningCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('guardian_created', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_registrations', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations_as_guardian', to=settings.AUTH_USER_MODEL)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coordinator', 'request_key'), name='unique_player_registration_request')],
            },
        ),
    ]
