# Generated by Django 5.2.17 on 2026-09-15 10:58

from django.db import migrations, models


def remove_school_staff_accounts(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    MemberRegistration = apps.get_model('accounts', 'MemberRegistration')
    staff_ids = list(
        User.objects.filter(role='SCHOOL_STAFF').values_list('pk', flat=True)
    )
    if not staff_ids:
        return

    # Coordinator-created account receipts use PROTECT. Remove those receipts
    # first; audit/history relations use SET_NULL and retain their records.
    MemberRegistration.objects.filter(member_id__in=staff_ids).delete()
    User.objects.filter(pk__in=staff_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_middle_initial'),
        ('academy', '0034_alter_trainingsession_date'),
    ]

    operations = [
        migrations.RunPython(remove_school_staff_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('COORDINATOR', 'Club Coordinator'), ('COACH', 'Coach'), ('PLAYER', 'Player'), ('GUARDIAN', 'Guardian')], default='PLAYER', max_length=20),
        ),
    ]
