# Generated by Django 5.2.15 on 2026-07-16 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('class_year', models.CharField(blank=True, max_length=40)),
                ('age_tier', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('DEVELOPMENT', 'Development'), ('PATHWAY', 'Pathway')], default='DEVELOPMENT', max_length=20)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('pace', models.PositiveSmallIntegerField(default=0)),
                ('shooting', models.PositiveSmallIntegerField(default=0)),
                ('passing', models.PositiveSmallIntegerField(default=0)),
                ('dribbling', models.PositiveSmallIntegerField(default=0)),
                ('defending', models.PositiveSmallIntegerField(default=0)),
                ('physical', models.PositiveSmallIntegerField(default=0)),
                ('eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('PENDING', 'Pending'), ('ACADEMIC_WARNING', 'Academic Warning')], default='PENDING', max_length=20)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=20)),
                ('end_time', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('focus', models.CharField(choices=[('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('MENTAL', 'Mental')], default='TECHNICAL', max_length=20)),
                ('age_tiers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='ABSENT', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academy.trainingsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
