# Generated by Django 5.2.15 on 2026-07-17 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_attendance_effort_attendance_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('body_part', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RECOVERING', 'Recovering'), ('RECOVERED', 'Recovered')], default='ACTIVE', max_length=20)),
                ('occurred_on', models.DateField()),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='injury_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
    ]
