# Generated by Django 5.2.15 on 2026-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_dispute_disputeresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEligibility',
            fields=[
            ],
            options={
                'verbose_name': 'Academic Eligibility',
                'verbose_name_plural': 'Academic Eligibility',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.playerprofile',),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
