# Generated by Django 5.2.15 on 2026-07-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_playereligibility_playerprofile_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined')], default='CONFIRMED', max_length=10)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_confirmations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='academy.trainingsession')),
            ],
            options={
                'ordering': ['-responded_at'],
                'unique_together': {('player', 'session')},
            },
        ),
    ]
