# Generated by Django 5.2.15 on 2026-07-18 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_sessionconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('PENDING', 'Pending'), ('ACADEMIC_WARNING', 'Academic Warning')], max_length=20)),
                ('new_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('PENDING', 'Pending'), ('ACADEMIC_WARNING', 'Academic Warning')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_changes_made', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eligibility history',
                'verbose_name_plural': 'Eligibility history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
