# Generated by Django 5.2.16 on 2026-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_eligibilityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='coach_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
