# Generated by Django 5.2.15 on 2026-07-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_playerprofile_coach_notes'),
        ('accounts', '0003_club_alter_user_role_user_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='accounts.club'),
        ),
    ]
