# Generated by Django 5.2.16 on 2026-07-23 14:58

from django.db import migrations, models


def seed_age_tiers(apps, schema_editor):
    """The three canonical bands from the requirements doc. Admin edits these
    rows afterwards; the tier set itself never changes."""
    AgeTierSetting = apps.get_model('academy', 'AgeTierSetting')
    for tier, min_age, max_age in (
        ('FOUNDATION', 10, 12),
        ('DEVELOPMENT', 13, 15),
        ('PATHWAY', 16, 18),
    ):
        AgeTierSetting.objects.get_or_create(
            tier=tier, defaults={'min_age': min_age, 'max_age': max_age}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_trainingsession_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeTierSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('DEVELOPMENT', 'Development'), ('PATHWAY', 'Pathway')], max_length=20, unique=True)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Age tier setting',
                'verbose_name_plural': 'Age tier settings',
                'ordering': ['min_age'],
            },
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='diving',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='handling',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='kicking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='positioning',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='reflexes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='speed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(seed_age_tiers, migrations.RunPython.noop),
    ]
