# Generated by Django 5.2.15 on 2026-08-26 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_alter_trainingsession_club_protect'),
        ('accounts', '0009_alter_club_coach_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=120)),
                ('competition', models.CharField(blank=True, max_length=120)),
                ('played_on', models.DateField()),
                ('venue', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('NEUTRAL', 'Neutral')], default='HOME', max_length=10)),
                ('our_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('opponent_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='football_matches', to='accounts.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_football_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=8)),
                ('starter', models.BooleanField(default=False)),
                ('minutes_played', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(180)])),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0)),
                ('passes_attempted', models.PositiveSmallIntegerField(default=0)),
                ('passes_completed', models.PositiveSmallIntegerField(default=0)),
                ('tackles', models.PositiveSmallIntegerField(default=0)),
                ('interceptions', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('red_cards', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)])),
                ('saves', models.PositiveSmallIntegerField(default=0)),
                ('goals_conceded', models.PositiveSmallIntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('coach_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='academy.footballmatch')),
                ('player', models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='match_performances', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_match_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match__played_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='footballmatch',
            index=models.Index(fields=['club', '-played_on'], name='academy_match_club_date_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchperformance',
            index=models.Index(fields=['player', 'match'], name='academy_perf_player_match_idx'),
        ),
        migrations.AddConstraint(
            model_name='playermatchperformance',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique_player_match_performance'),
        ),
        migrations.AddConstraint(
            model_name='playermatchperformance',
            constraint=models.CheckConstraint(condition=models.Q(('shots_on_target__lte', models.F('shots'))), name='shots_on_target_lte_shots'),
        ),
        migrations.AddConstraint(
            model_name='playermatchperformance',
            constraint=models.CheckConstraint(condition=models.Q(('goals__lte', models.F('shots_on_target'))), name='goals_lte_shots_on_target'),
        ),
        migrations.AddConstraint(
            model_name='playermatchperformance',
            constraint=models.CheckConstraint(condition=models.Q(('passes_completed__lte', models.F('passes_attempted'))), name='passes_completed_lte_attempted'),
        ),
    ]
