# Generated by Django 5.2.15 on 2026-08-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_injury_history(apps, schema_editor):
    InjuryRecord = apps.get_model('academy', 'InjuryRecord')
    for record in InjuryRecord.objects.iterator():
        record.reported_by_id = record.player_id
        record.review_status = 'CONFIRMED'
        record.save(update_fields=['reported_by', 'review_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_split_match_statistics_and_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_injuries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_injuries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            preserve_existing_injury_history,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='InjuryStatusUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RECOVERING', 'Recovering'), ('RECOVERED', 'Recovered')], max_length=20)),
                ('proposed_resolved_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_update_requests', to='academy.injuryrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_injury_status_updates', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_injury_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('review_status', 'PENDING')), fields=('injury',), name='academy_one_pending_injury_update')],
            },
        ),
    ]
