# Generated by Django 5.2.17 on 2026-09-09 11:41

import hashlib
import json

import django.utils.timezone
from django.db import migrations, models


def chain_existing_entries(apps, schema_editor):
    AuditLog = apps.get_model('academy', 'AuditLog')
    previous_hash = ''
    for entry in AuditLog.objects.order_by('created_at', 'id').iterator():
        payload = json.dumps({
            'previous_hash': previous_hash,
            'action': entry.action,
            'target': entry.target,
            'detail': entry.detail,
            'created_at': entry.created_at.isoformat(),
        }, sort_keys=True, separators=(',', ':')).encode('utf-8')
        entry_hash = hashlib.sha256(payload).hexdigest()
        AuditLog.objects.filter(pk=entry.pk).update(
            previous_hash=previous_hash,
            entry_hash=entry_hash,
        )
        previous_hash = entry_hash


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0029_player_stats_validators_and_focus_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RunPython(chain_existing_entries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
