# Generated by Django 5.2.17 on 2026-09-10 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0031_audit_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('user_ids', models.JSONField(default=list)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=300)),
                ('data', models.JSONField(default=dict)),
                ('pending_tokens', models.JSONField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_id', models.UUIDField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['completed_at', 'available_at'], name='push_outbox_due_idx')],
            },
        ),
    ]
