# Generated by Django 5.2.17 on 2026-09-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0033_attendance_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
