from django.urls import path

from . import views

urlpatterns = [
    path('players/', views.SquadListView.as_view(), name='players-list'),
    path('players/me/', views.MyProfileView.as_view(), name='players-me'),
    path('players/linked/', views.LinkedPlayersView.as_view(), name='players-linked'),
    path(
        'players/<int:player_id>/profile/',
        views.PlayerDetailView.as_view(),
        name='player-detail',
    ),
    path(
        'players/<int:player_id>/pin/',
        views.PlayerPrivacyPinView.as_view(),
        name='player-pin',
    ),
    path(
        'players/<int:player_id>/pin/verify/',
        views.PlayerPrivacyPinVerifyView.as_view(),
        name='player-pin-verify',
    ),
    path(
        'players/<int:player_id>/pin/reset/',
        views.PlayerPrivacyPinResetView.as_view(),
        name='player-pin-reset',
    ),
    path(
        'players/<int:player_id>/assessment/',
        views.PlayerAssessmentView.as_view(),
        name='player-assessment',
    ),
    path(
        'players/<int:player_id>/assessment-history/',
        views.PlayerAssessmentHistoryView.as_view(),
        name='player-assessment-history',
    ),
    path(
        'players/<int:player_id>/match-statistics/',
        views.PlayerMatchStatisticsView.as_view(),
        name='player-match-statistics',
    ),
    path(
        'players/<int:player_id>/growth/',
        views.PlayerGrowthView.as_view(),
        name='player-growth',
    ),
    path(
        'players/<int:player_id>/position/',
        views.PlayerPositionView.as_view(),
        name='player-position',
    ),
    path(
        'players/<int:player_id>/eligibility-history/',
        views.EligibilityHistoryView.as_view(),
        name='eligibility-history',
    ),
    path('age-tiers/', views.AgeTierSettingsView.as_view(), name='age-tiers'),
    path(
        'progress/squad/',
        views.SquadProgressView.as_view(),
        name='progress-squad',
    ),
    path(
        'tournament-schedules/',
        views.TournamentScheduleListView.as_view(),
        name='tournament-schedules',
    ),
    path(
        'tournament-schedules/<int:schedule_id>/',
        views.TournamentScheduleDetailView.as_view(),
        name='tournament-schedule-detail',
    ),
    path(
        'tournament-schedules/<int:schedule_id>/publish/',
        views.TournamentSchedulePublishView.as_view(),
        name='tournament-schedule-publish',
    ),
    path(
        'tournament-schedules/<int:schedule_id>/document/',
        views.TournamentScheduleDocumentView.as_view(),
        name='tournament-schedule-document',
    ),
    path(
        'tournament-schedules/<int:schedule_id>/fixtures/',
        views.TournamentFixtureCreateView.as_view(),
        name='tournament-fixture-create',
    ),
    path(
        'tournament-fixtures/<int:fixture_id>/',
        views.TournamentFixtureDetailView.as_view(),
        name='tournament-fixture-detail',
    ),
    path(
        'tournament-fixtures/<int:fixture_id>/result/',
        views.TournamentFixtureResultView.as_view(),
        name='tournament-fixture-result',
    ),
    path(
        'tournament-schedules/<int:schedule_id>/brackets/',
        views.TournamentAgeBracketCreateView.as_view(),
        name='tournament-bracket-create',
    ),
    path(
        'tournament-brackets/<int:bracket_id>/',
        views.TournamentAgeBracketDetailView.as_view(),
        name='tournament-bracket-detail',
    ),
    path(
        'tournament-brackets/<int:bracket_id>/squad/',
        views.TournamentSquadDetailView.as_view(),
        name='tournament-squad-detail',
    ),
    path(
        'tournament-brackets/<int:bracket_id>/squad/candidates/',
        views.TournamentSquadCandidatesView.as_view(),
        name='tournament-squad-candidates',
    ),
    path(
        'tournament-brackets/<int:bracket_id>/squad/publish/',
        views.TournamentSquadPublishView.as_view(),
        name='tournament-squad-publish',
    ),
    path(
        'matches/',
        views.FootballMatchListCreateView.as_view(),
        name='football-matches',
    ),
    path(
        'matches/<int:match_id>/',
        views.FootballMatchDetailView.as_view(),
        name='football-match-detail',
    ),
    path(
        'matches/<int:match_id>/performances/',
        views.MatchPerformanceListView.as_view(),
        name='match-performances',
    ),
    path(
        'matches/<int:match_id>/roster/',
        views.MatchRosterView.as_view(),
        name='match-roster',
    ),
    path(
        'matches/<int:match_id>/performances/<int:player_id>/',
        views.MatchPerformanceDetailView.as_view(),
        name='match-performance-detail',
    ),
    path(
        'matches/<int:match_id>/performances/<int:player_id>/rating/',
        views.MatchPerformanceRatingView.as_view(),
        name='match-performance-rating',
    ),
    path('attendance/', views.AttendanceListView.as_view(), name='attendance-list'),
    path(
        'attendance/session/<int:session_id>/',
        views.SessionAttendanceView.as_view(),
        name='attendance-session',
    ),
    path(
        'training-sessions/',
        views.TrainingSessionListCreateView.as_view(),
        name='training-sessions',
    ),
    path(
        'training-sessions/<int:pk>/',
        views.TrainingSessionDetailView.as_view(),
        name='training-session-detail',
    ),
    path(
        'session-confirmations/',
        views.SessionConfirmationView.as_view(),
        name='session-confirmations',
    ),
    path('disputes/', views.DisputeListCreateView.as_view(), name='disputes'),
    path(
        'disputes/<int:pk>/',
        views.DisputeDetailView.as_view(),
        name='dispute-detail',
    ),
    path(
        'disputes/<int:pk>/responses/',
        views.DisputeResponseCreateView.as_view(),
        name='dispute-responses',
    ),
    path(
        'injuries/',
        views.InjuryWorkflowListCreateView.as_view(),
        name='injuries',
    ),
    path(
        'injuries/reportable-players/',
        views.InjuryReportablePlayersView.as_view(),
        name='injury-reportable-players',
    ),
    path(
        'injuries/<int:pk>/',
        views.InjuryWorkflowDetailView.as_view(),
        name='injury-detail',
    ),
    path(
        'injuries/<int:pk>/review/',
        views.InjuryReviewView.as_view(),
        name='injury-review',
    ),
    path(
        'injuries/<int:pk>/archive/',
        views.InjuryArchiveView.as_view(),
        name='injury-archive',
    ),
    path(
        'injuries/<int:pk>/status-updates/',
        views.InjuryStatusUpdateListCreateView.as_view(),
        name='injury-status-updates',
    ),
    path(
        'injuries/<int:pk>/status-updates/<int:update_id>/review/',
        views.InjuryStatusUpdateReviewView.as_view(),
        name='injury-status-update-review',
    ),
    path('devices/', views.DeviceRegisterView.as_view(), name='devices'),
    path(
        'notifications/',
        views.NotificationListView.as_view(),
        name='notifications',
    ),
    path(
        'notifications/unread-count/',
        views.NotificationUnreadCountView.as_view(),
        name='notification-unread-count',
    ),
    path(
        'notifications/read-all/',
        views.NotificationReadAllView.as_view(),
        name='notification-read-all',
    ),
    path(
        'notifications/<int:pk>/read/',
        views.NotificationReadView.as_view(),
        name='notification-read',
    ),
    path(
        'players/<int:player_id>/photo/',
        views.PlayerPhotoUploadView.as_view(),
        name='player-photo-upload-mobile',
    ),
    path(
        'admin/players/',
        views.AdminCreatePlayerView.as_view(),
        name='admin-player-create',
    ),
    path(
        'admin/players/<int:player_id>/photo/',
        views.PlayerPhotoUploadView.as_view(),
        name='player-photo-upload',
    ),
]
