"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# True while running `manage.py test`. Used to force isolated/local services
# and to keep tests from emitting production telemetry.
TESTING = 'test' in sys.argv

# Optional production error monitoring. The integration is inert unless a
# DSN is supplied, so local development and tests never send telemetry.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
if SENTRY_DSN and not TESTING:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        release=os.environ.get('RELEASE_SHA') or None,
        send_default_pii=False,
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.05')),
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG') == '1'

# 10.0.2.2 is the Android emulator's loopback to the host machine. In
# production, set DJANGO_ALLOWED_HOSTS (comma-separated) to the real hostnames.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.0.2.2']
_extra_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]
if not DEBUG and not _extra_hosts:
    raise ImproperlyConfigured(
        'DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG=0.'
    )
if not DEBUG and (len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 10):
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be a long, high-entropy production secret.'
    )


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    # Brute-force / credential-stuffing protection for the session logins
    # (/portal/login/ and /admin/). Inert for the Firebase API, which Firebase
    # rate-limits itself. See AXES_* below (audit finding S1).
    'axes',
    'accounts',
    'academy',
    'console',
    'portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Strict Content-Security-Policy + security headers for the /portal/ pages.
    'portal.middleware.PortalSecurityHeadersMiddleware',
    # django-axes must be the LAST middleware so it sees the resolved user.
    'axes.middleware.AxesMiddleware',
]
if TESTING:
    # Tests exercise application behavior, not collected-static serving, and
    # a fresh checkout intentionally has no generated staticfiles directory.
    MIDDLEWARE.remove('whitenoise.middleware.WhiteNoiseMiddleware')

# django-axes plugs in ahead of the normal ModelBackend so a locked-out
# (username, IP) pair is rejected before any password is even checked. The
# standalone backend does not authenticate itself — it only gates — so the
# regular ModelBackend still does the real login.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Default is local SQLite so a fresh clone (and the test suite) runs with zero
# setup. Set the DB_* env vars (see .env.example) to point at a shared Postgres
# such as Supabase. Supabase IS Postgres, so nothing but this connection block
# changes — Django stays the source of truth; we do NOT use Supabase Auth/RLS.
# The test suite always uses SQLite (see TESTING above), never the shared DB.
if os.environ.get('DB_HOST') and not TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'require'),
            },
            # Supabase's transaction pooler (port 6543) doesn't support the
            # server-side cursors Django uses by default; harmless on 5432.
            'DISABLE_SERVER_SIDE_CURSORS': os.environ.get('DB_PORT') == '6543',
        }
    }
elif TESTING or DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        'DB_HOST must be set in production; local SQLite is only available '
        'for development and automated tests.'
    )


# Password hashing — Argon2id first (via argon2-cffi); PBKDF2 kept so existing
# hashes still verify and get upgraded to Argon2 on next login.
# https://docs.djangoproject.com/en/5.2/topics/auth/passwords/

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if TESTING
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Uploaded files (coach licenses submitted at club registration). Kept out of
# git (see .gitignore); in DEBUG they are served by config/urls.py. A hard size
# cap is enforced in the signup form; this is a request-body backstop.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 6 MB request-body backstop

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model — must be set before the first migrate ever runs.
AUTH_USER_MODEL = 'accounts.User'

# Session-authenticated web portal (coordinators / school staff). App users
# authenticate via Firebase and never reach these pages.
LOGIN_URL = '/portal/login/'
LOGIN_REDIRECT_URL = '/portal/'
LOGOUT_REDIRECT_URL = '/portal/login/'

# Django defaults this to 'DENY'. Jazzmin's related_modal_active loads admin
# add/change forms in a same-origin iframe, so allow same-origin framing.
X_FRAME_OPTIONS = 'SAMEORIGIN'

# CORS. In development, Flutter web runs on a random localhost port each launch,
# so allow all origins. In production, allow only the explicit origins from
# CORS_ORIGINS (comma-separated) — never wildcard (audit finding F5).
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in os.environ.get('CORS_ORIGINS', '').split(',') if o.strip()
    ]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Structured-enough console logs for container aggregation. Request bodies,
# tokens, passwords, and student data are deliberately not added to log lines.
LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'production': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'production',
        },
    },
    'root': {'handlers': ['console'], 'level': LOG_LEVEL},
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Cache. LocMemCache needs no external service, so a fresh clone and the test
# suite work with zero setup. It is per-process, so a multi-worker deployment
# should point this at a shared backend (Redis/Memcached) — otherwise the
# axes lockout counters, the signup rate limiter, and the read-revocation
# window below are only consistent within a single worker.
REDIS_URL = os.environ.get('REDIS_URL', '')
if not DEBUG and not TESTING and not REDIS_URL:
    raise ImproperlyConfigured('REDIS_URL must be set in production.')
CACHES = (
    {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
    if not DEBUG and not TESTING
    else {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'footpath-local',
        }
    }
)

# django-axes (audit finding S1) — lock out brute-force / credential-stuffing
# against the Django session logins.
#   * Disabled under `manage.py test` so the suite's repeated logins don't trip
#     the limiter (the threat model is production traffic, not the tests).
#   * Locks on the (username, IP) pair, not username alone, so an attacker
#     cannot lock a legitimate user out of their account just by guessing their
#     email (account-lockout denial of service).
#   * A successful login clears the counter for that pair.
AXES_ENABLED = not TESTING
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
# Behind a TLS-terminating proxy in production, tell axes how many proxies sit
# in front so it reads the real client IP from X-Forwarded-For rather than the
# proxy's. Left at 0 for local development (no proxy).
AXES_IPWARE_PROXY_COUNT = int(os.environ.get('AXES_PROXY_COUNT', '0'))

# Cache-backed rate limiting for the public, unauthenticated portal endpoints
# (portal.ratelimit — audit finding S3). Off during tests so unrelated suites
# that post repeatedly are not throttled.
RATELIMIT_ENABLE = not TESTING

# Production security hardening (audit finding F6). Applied only when DEBUG is
# off so local HTTP development is unaffected. `manage.py check --deploy` should
# be clean with these set. Assumes TLS is terminated by a proxy that sets
# X-Forwarded-Proto.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Path to the Firebase Admin SDK service-account JSON (kept out of git).
FIREBASE_CREDENTIALS = BASE_DIR / os.environ.get(
    'FIREBASE_CREDENTIALS', 'secrets/firebase-service-account.json'
)

# django-jazzmin: theme for the built-in /admin/ site.
JAZZMIN_SETTINGS = {
    'site_title': 'FootPath Cebu Admin',
    'site_header': '⚽ FootPath Cebu',
    'site_brand': '⚽ FootPath Cebu',
    'welcome_sign': 'FootPath Cebu — Admin Console',
    'copyright': 'FootPath Cebu',
    'search_model': ['accounts.User'],
    'user_avatar': None,
    'icons': {
        'accounts.User': 'fas fa-user',
        'accounts.GuardianLink': 'fas fa-link',
        'accounts.Club': 'fas fa-shield-alt',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'order_with_respect_to': ['accounts'],
    # Groups are unused (authorization is via User.role), so hide the now-empty
    # 'Authentication and Authorization' app from the sidebar.
    'hide_apps': ['auth'],
    # Brand polish: role/status pill badges, slate-charcoal palette, Inter font.
    'custom_css': 'footpath/admin.css',
    # Control-bar enhancer: rename bulk-action placeholder + relocate the toolbar.
    'custom_js': 'footpath/admin.js',
    # Add/edit related objects (e.g. picking a Group on the user form) in a
    # popup modal instead of navigating away to a new page.
    'related_modal_active': True,
    'changeform_format': 'horizontal_tabs',
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    # Light by default to match the custom console (/console/); the navbar
    # toggle still offers dark.
    'default_theme_mode': 'light',
    'navbar': 'navbar-white navbar-light',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'accent': 'accent-success',
    'sidebar': 'sidebar-light-success',
    'sidebar_fixed': True,
    'sidebar_nav_flat_style': True,
}
