"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# True while running `manage.py test`. Used to force SQLite for the test suite
# even when DB_* env vars point at a shared Postgres, so tests stay fast, run
# offline, and never create a throwaway test DB on Supabase.
TESTING = 'test' in sys.argv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG') == '1'

# 10.0.2.2 is the Android emulator's loopback to the host machine.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.0.2.2']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'console',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Default is local SQLite so a fresh clone (and the test suite) runs with zero
# setup. Set the DB_* env vars (see .env.example) to point at a shared Postgres
# such as Supabase. Supabase IS Postgres, so nothing but this connection block
# changes — Django stays the source of truth; we do NOT use Supabase Auth/RLS.
# The test suite always uses SQLite (see TESTING above), never the shared DB.
if os.environ.get('DB_HOST') and not TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {'sslmode': 'require'},
            # Supabase's transaction pooler (port 6543) doesn't support the
            # server-side cursors Django uses by default; harmless on 5432.
            'DISABLE_SERVER_SIDE_CURSORS': os.environ.get('DB_PORT') == '6543',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model — must be set before the first migrate ever runs.
AUTH_USER_MODEL = 'accounts.User'

# Django defaults this to 'DENY'. Jazzmin's related_modal_active loads admin
# add/change forms in a same-origin iframe, so allow same-origin framing.
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Dev only: Flutter web runs on a random localhost port each launch.
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Path to the Firebase Admin SDK service-account JSON (kept out of git).
FIREBASE_CREDENTIALS = BASE_DIR / os.environ.get(
    'FIREBASE_CREDENTIALS', 'secrets/firebase-service-account.json'
)

# django-jazzmin: theme for the built-in /admin/ site.
JAZZMIN_SETTINGS = {
    'site_title': 'FootPath Cebu Admin',
    'site_header': 'FootPath Cebu',
    'site_brand': 'FootPath Cebu',
    'welcome_sign': 'FootPath Cebu Admin',
    'copyright': 'FootPath Cebu',
    'search_model': ['accounts.User'],
    'user_avatar': None,
    'topmenu_links': [
        {'name': 'Admin Console', 'url': '/console/', 'new_window': True},
    ],
    'icons': {
        'accounts.User': 'fas fa-user',
        'accounts.GuardianLink': 'fas fa-link',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'order_with_respect_to': ['accounts'],
    # Groups are unused (authorization is via User.role), so hide the now-empty
    # 'Authentication and Authorization' app from the sidebar.
    'hide_apps': ['auth'],
    # Brand polish: role/status pill badges, slate-charcoal palette, Inter font.
    'custom_css': 'footpath/admin.css',
    # Control-bar enhancer: rename bulk-action placeholder + relocate the toolbar.
    'custom_js': 'footpath/admin.js',
    # Add/edit related objects (e.g. picking a Group on the user form) in a
    # popup modal instead of navigating away to a new page.
    'related_modal_active': True,
    'changeform_format': 'horizontal_tabs',
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    # Default to the dark (charcoal) palette; navbar toggle still switches it.
    'default_theme_mode': 'dark',
    'navbar': 'navbar-dark',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'accent': 'accent-success',
    'sidebar': 'sidebar-dark-success',
    'sidebar_fixed': True,
    'sidebar_nav_flat_style': True,
}
