// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHeJwmqiXuYbjAsi0-jjwF3i6nbfgLyc',
    appId: '1:155194186459:web:02f9e43d070c98fc8ecafe',
    messagingSenderId: '155194186459',
    projectId: 'footpath-cebu',
    authDomain: 'footpath-cebu.firebaseapp.com',
    storageBucket: 'footpath-cebu.firebasestorage.app',
    measurementId: 'G-QFC0S3T6S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfYsvLzEuC6pteIKZVPmoAy6EK1DyQBI',
    appId: '1:155194186459:android:1d9675f5df6df5de8ecafe',
    messagingSenderId: '155194186459',
    projectId: 'footpath-cebu',
    storageBucket: 'footpath-cebu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK7Ek-fjQx84fdS9TqXPeSQc8ivvXtjuI',
    appId: '1:155194186459:ios:a0974b9e57bd65ba8ecafe',
    messagingSenderId: '155194186459',
    projectId: 'footpath-cebu',
    storageBucket: 'footpath-cebu.firebasestorage.app',
    iosBundleId: 'com.example.footpathCebu',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK7Ek-fjQx84fdS9TqXPeSQc8ivvXtjuI',
    appId: '1:155194186459:ios:a0974b9e57bd65ba8ecafe',
    messagingSenderId: '155194186459',
    projectId: 'footpath-cebu',
    storageBucket: 'footpath-cebu.firebasestorage.app',
    iosBundleId: 'com.example.footpathCebu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHeJwmqiXuYbjAsi0-jjwF3i6nbfgLyc',
    appId: '1:155194186459:web:bd75f3c6d782aacc8ecafe',
    messagingSenderId: '155194186459',
    projectId: 'footpath-cebu',
    authDomain: 'footpath-cebu.firebaseapp.com',
    storageBucket: 'footpath-cebu.firebasestorage.app',
    measurementId: 'G-6XKCCCQMJD',
  );
}
